name: Build Kotlin/WASM and Deploy to Cloudflare

on:
  push:
    branches: [main]
    
jobs:
  build:
    name: Build Kotlin/WASM App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Java for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 24
          
      - name: Cache Gradle and Konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}
          
      - name: Build
        run: |
          ./gradlew --stacktrace wasmJsBrowserDistribution --no-daemon --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-app
          path: composeApp/build/dist/wasmJs/productionExecutable

  deploy:
    name: Deploy to Cloudflare
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: wasm-app
          path: wasm-app

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Create package.json
        run: |
          echo '{ "private": true, "dependencies": { "wrangler": "4.15.2" } }' > package.json

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package.json') }}
          restore-keys: ${{ runner.os }}-node-modules-

      - name: Install wrangler
        run: npm install

      - name: Deploy with wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd wasm-app
          npx wrangler deploy --config wrangler.jsonc